services:
  web:
    build:
      context: ..
      dockerfile: Dockerfile.dev
    container_name: web
    restart: always
    volumes:
    # reference changes made in working directory of the application
      - ./:/usr/src/app
    ports:
      - 3000:3000

# sudo docker-compose up
#   If a docker image has not been built it will be created