name: Trigger auto deployment for somotracker-web

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/somotracker-web-AutoDeployTrigger-a4a91ccc-82b4-4649-abde-521904c8355f.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: somotracker.azurecr.io
          username: ${{ secrets.SOMOTRACKERWEB_REGISTRY_USERNAME }}
          password: ${{ secrets.SOMOTRACKERWEB_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: somotracker.azurecr.io/somotracker-web:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SOMOTRACKERWEB_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n somotracker-web -g somotracker-1 --server somotracker.azurecr.io --username  ${{ secrets.SOMOTRACKERWEB_REGISTRY_USERNAME }} --password ${{ secrets.SOMOTRACKERWEB_REGISTRY_PASSWORD }}
            az containerapp update -n somotracker-web -g somotracker-1 --image somotracker.azurecr.io/somotracker-web:${{ github.sha }}
